update environments on deploy

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -29,8 +29,6 @@ steps:
           echo "ABIs not up-to-date in packages/sdk, need to run 'npm run refresh-abis'"
           exit 1
         fi
-    depends_on:
-    # nothing
 
   - name: check-subgraph-abi
     image: node:18.19
@@ -43,8 +41,6 @@ steps:
           echo "ABIs not up-to-date in packages/subgraph, need to run 'npm run refresh-abis'"
           exit 1
         fi
-    depends_on:
-    # nothing
 
   - name: check-dapp-abi
     image: node:18.19
@@ -57,8 +53,6 @@ steps:
           echo "ABIs not up-to-date in protected-data-delivery-dapp/abis, need to run 'npm run refresh-abis'"
           exit 1
         fi
-    depends_on:
-    # nothing
 
 ---
 # deploy DataProtector smart contract in prod, dev or staging
@@ -184,6 +178,251 @@ steps:
     commands:
       - cd packages/smart-contract
       - npm run verify -- --network bellecour $(cat .smart-contract-address) $(cat .constructor-args-params)
+
+---
+# deploy sharing smart contract in prod, staging or dev
+kind: pipeline
+type: docker
+name: deploy-sharing-smart-contract
+
+trigger:
+  event:
+    - promote
+  target:
+    - sharing-smart-contract-dev
+    - sharing-smart-contract-staging
+    - sharing-smart-contract-production
+  branch:
+    - develop
+    - main
+    - v2
+
+steps:
+  - name: install-deps
+    image: node:18.19
+    pull: always
+    commands:
+      - cd packages/sharing-smart-contract
+      - node -v
+      - npm -v
+      - npm ci
+
+  - name: install-forge
+    image: node:18.19
+    pull: always
+    commands:
+      - export XDG_CONFIG_HOME=/drone/src
+      - curl -L https://foundry.paradigm.xyz | bash
+      - export PATH="$PATH:/drone/src/.foundry/bin"
+      - foundryup
+      - forge install foundry-rs/forge-std --no-git
+
+  - name: bellecour-fork
+    detach: true
+    image: ghcr.io/foundry-rs/foundry:latest
+    pull: always
+    expose:
+      - 8545
+    commands:
+      - anvil --host 0.0.0.0 --port 8545 --hardfork berlin --fork-url https://bellecour.iex.ec --chain-id 134 --gas-limit 6700000 --gas-price 0
+
+  - name: bellecour-fork-healthy
+    image: bash
+    commands:
+      - while ! nc -z bellecour-fork 8545 ; do sleep 1 ; done && echo "bellecour-fork ready"
+    depends_on:
+      - bellecour-fork
+
+  - name: compile
+    image: node:18.19
+    commands:
+      - cd packages/sharing-smart-contract
+      - export PATH="$PATH:/drone/src/.foundry/bin"
+      - npm run compile
+    depends_on:
+      - install-forge
+      - install-deps
+
+  - name: check format
+    image: node:18.19
+    commands:
+      - cd packages/sharing-smart-contract
+      - npm run check-format
+    depends_on:
+      - install-deps
+
+  - name: lint
+    image: node:18.19
+    commands:
+      - cd packages/sharing-smart-contract
+      - npm run lint
+    depends_on:
+      - install-deps
+
+  - name: uml-diagrams
+    image: node:18.19
+    commands:
+      - cd packages/sharing-smart-contract
+      - npm run uml
+    depends_on:
+      - install-deps
+
+  - name: static-analyzer
+    image: node:18.19
+    commands:
+      - cd packages/sharing-smart-contract
+      - git clone https://github.com/Picodes/4naly3er.git
+      - cd 4naly3er
+      - git reset --hard HEAD~1 # FIX issue https://github.com/Picodes/4naly3er/issues/48
+      - yarn install
+      - yarn analyze ../contracts
+    depends_on:
+      - compile
+      - lint
+
+  - name: hardhat-tests
+    image: node:18.19
+    commands:
+      - cd packages/sharing-smart-contract
+      - export PATH="$PATH:/drone/src/.foundry/bin"
+      - npm run test -- --network ci-bellecour-fork
+    depends_on:
+      - install-deps
+      - install-forge
+      - bellecour-fork-healthy
+
+  - name: forge-tests
+    image: node:18.19
+    commands:
+      - cd packages/sharing-smart-contract
+      - export PATH="$PATH:/drone/src/.foundry/bin"
+      - forge test --no-match-test "invariant" -vvvvv
+    depends_on:
+      - install-deps
+      - install-forge
+      - bellecour-fork-healthy
+
+  - name: smart-contract-dev-deployment
+    image: node:18.19
+    environment:
+      WALLET_PRIVATE_KEY:
+        from_secret: deployer-dev-privatekey
+    commands:
+      - cd packages/sharing-smart-contract
+      - npm run deploy -- --network bellecour
+    depends_on:
+      - compile
+      - forge-tests
+      - hardhat-tests
+    when:
+      target:
+        - sharing-smart-contract-dev
+      branch:
+        - develop
+        - v2
+
+  - name: smart-contract-staging-deployment
+    image: node:18.19
+    environment:
+      WALLET_PRIVATE_KEY:
+        from_secret: deployer-dev-privatekey
+      ENV: staging
+    commands:
+      - cd packages/sharing-smart-contract
+      - npm run deploy -- --network bellecour
+    depends_on:
+      - compile
+      - forge-tests
+      - hardhat-tests
+    when:
+      target:
+        - sharing-smart-contract-staging
+      branch:
+        - develop
+        - v2
+
+  - name: smart-contract-prod-deployment
+    image: node:18.19
+    environment:
+      WALLET_PRIVATE_KEY:
+        from_secret: deployer-prod-privatekey
+    commands:
+      - cd packages/sharing-smart-contract
+      - npm run deploy -- --network bellecour
+    depends_on:
+      - compile
+      - forge-tests
+      - hardhat-tests
+    when:
+      target:
+        - sharing-smart-contract-production
+      branch:
+        - main
+        - v2
+
+  - name: update-prod-env
+    image: node:18.19
+    commands:
+      - cd environments
+      - ENV=prod KEY=DataProtectorSharingContractAddress VALUE=$(cat ../packages/sharing-smart-contract/DataProtectorSharing.smart-contract-address) npm run update-env
+      - ENV=prod KEY=AddOnlyAppWhitelistRegistryAddress VALUE=$(cat ../packages/sharing-smart-contract/AppWhitelistRegistry.smart-contract-address) npm run update-env
+      - git add environments.json
+      - git commit -m "$DRONE_DEPLOY_TO deployment $DRONE_BUILD_NUMBER $DRONE_COMMIT" --author="drone-product <team-product@iex.ec>"
+    when:
+      target:
+        - sharing-smart-contract-production
+    depends_on:
+      - smart-contract-prod-deployment
+
+  - name: update-staging-env
+    image: node:18.19
+    commands:
+      - cd environments
+      - ENV=staging KEY=DataProtectorSharingContractAddress VALUE=$(cat ../packages/sharing-smart-contract/DataProtectorSharing.smart-contract-address) npm run update-env
+      - ENV=prod KEY=AddOnlyAppWhitelistRegistryAddress VALUE=$(cat ../packages/sharing-smart-contract/AppWhitelistRegistry.smart-contract-address) npm run update-env
+      - git add environments.json
+      - git commit -m "$DRONE_DEPLOY_TO deployment $DRONE_BUILD_NUMBER $DRONE_COMMIT" --author="drone-product <team-product@iex.ec>"
+    when:
+      target:
+        - sharing-smart-contract-staging
+    depends_on:
+      - smart-contract-staging-deployment
+
+  - name: push update-env
+    image: appleboy/drone-git-push
+    settings:
+      remote: ssh://git@github.com/iExecBlockchainComputing/dataprotector-sdk.git
+      branch: update-env-${DRONE_BUILD_NUMBER}
+      ssh_key:
+        from_secret: ssh-key-team-product-github-push
+    when:
+      target:
+        - sharing-smart-contract-production
+        - sharing-smart-contract-staging
+    depends_on:
+      - update-prod-env
+      - update-staging-env
+
+  # TODO : Fix
+  # - name: verify contract
+  #   image: node:18.19
+  #   commands:
+  #     - cd packages/sharing-smart-contract
+  #     - timeout 30 npm run verify -- --network bellecour $(cat DataProtectorSharing.smart-contract-address) $(cat DataProtectorSharing.constructor-args-params) || echo "verification may have failed, check at https://blockscout-bellecour.iex.ec/address/$(cat DataProtectorSharing.smart-contract-address)/contracts#address-tabs"
+  #     - timeout 30 npm run verify -- --network bellecour $(cat AppWhitelistRegistry.smart-contract-address) $(cat AppWhitelistRegistry.constructor-args-params) || echo "verification may have failed, check at https://blockscout-bellecour.iex.ec/address/$(cat AppWhitelistRegistry.smart-contract-address)/contracts#address-tabs"
+  #   when:
+  #     depends_on:
+  #      - smart-contract-dev-deployment
+  #      - smart-contract-staging-deployment
+  #      - smart-contract-prod-deployment
+  #     target:
+  #       - sharing-smart-contract-dev
+  #       - sharing-smart-contract-staging
+  #       - sharing-smart-contract-production
+  #     branch:
+  #       - develop
+  #       - main
+  #       - v2
 
 ---
 kind: pipeline
